
name: Tribblix

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - '**.py'
      - '.github/workflows/tribblix.yml'
      - '.github/workflows/testrun.yml'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: >-
      ${{ github.event_name != 'push'
          || (
               ( !contains(github.event.head_commit.message, '[testos=')
                 || contains(github.event.head_commit.message, '[testos=tribblix]') )
            && ( !contains(github.event.head_commit.message, '[testhost=')
                 || contains(github.event.head_commit.message, '[testhost=linux') )
             ) }}
    strategy:
      fail-fast: false
      matrix:
        release: ["0m39", "0m40", "0m41"]
        arch: [""]
        runs: ["ubuntu-24.04"]
        sync: [ "scp", "nfs", "rsync", "tar"]


    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: tribblix
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: ${{ matrix.sync }}
